apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
    #   version: latest
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: default
      interval: 1m
  values:
    controller:
        autoscaling:
            enabled: true
            minReplicas: 2
        hostNetwork: true
        service:
            type: NodePort