kind: Service
apiVersion: v1
metadata:
    name: pihole-web
    namespace : pihole
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole
spec:
    selector:
      app: pihole
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name : web
    type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
    name: pihole-dns-udp
    namespace: pihole
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole
spec:
    selector:
      app: pihole
    ports:
    - port: 53
      protocol: UDP
      targetPort: 53
      name : dnsudp
    type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
    name: pihole-dns-tcp
    namespace: pihole
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole
spec:
    selector:
      app: pihole
    ports:
    - port: 53
      protocol: TCP
      targetPort: 53
      name : dnstcp
    type: LoadBalancer