apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
    #   version: latest
      sourceRef:
        kind: HelmRepository
        name: prometheus-stack
        namespace: monitoring
      interval: 1m